Remove mcid overriding
veraPDF/pdf.js pull request #17
Opened 2024-02-19 14:41 UTC by GribovskyPavel

2024-02-19 14:50 UTC, GribovskyPavel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Paragraph is shown differently from Acrobat](https://trello.com/c/NZ8iM9SX/475-paragraph-is-shown-differently-from-acrobat)

2024-02-20 12:03 UTC, KateOrient requested changes

2024-02-20 12:03 UTC, KateOrient commented on src/core/bounding_boxes.js
> +      if (fn === OPS.beginMarkedContentProps && isDict(args[1]) && args[1].has('MCID')) {
Move this to `case OPS.beginMarkedContentProps`

2024-02-20 12:03 UTC, KateOrient commented on src/core/bounding_boxes.js
> +      if (fn === OPS.endMarkedContent && this.sameMcidDepth !== 0) {
Move this to `case OPS.endMarkedContent`

2024-02-20 12:30 UTC, KateOrient requested changes

2024-02-20 12:30 UTC, KateOrient commented on src/core/bounding_boxes.js
> +              return;
Use break instead of return as we don't have any logic after switch

2024-02-20 12:30 UTC, KateOrient commented on src/core/bounding_boxes.js
> +            return;
Use break instead of return as we don't have any logic after switch

2024-02-20 12:38 UTC, KateOrient approved these changes

2024-02-20 13:25 UTC, merged